apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    app: monitoring
    component: prometheus
    managed-by: gitops
  annotations:
    reloader.stakater.com/match: "true"
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'telegraf'
        static_configs:
          - targets: ['localhost:9273']
