apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: default
  labels:
    app: monitoring
    component: telegraf
    managed-by: gitops
  annotations:
    reloader.stakater.com/match: "true"
data:
  telegraf.conf: |
    [agent]
      interval = "10s"
      round_interval = true
      omit_hostname = false

    [[outputs.prometheus_client]]
      listen = ":9273"
      path = "/metrics"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = true
